[package]
name = "druid-example"
version = "0.1.0"
authors = ["Marvinesc3 <Marvinesc3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.6.0"
ggez = "0.5.1"